version: '3'
services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - storage
    environment:
      - AzureWebJobsStorage="UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://host.docker.internal"
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
