version: '3'
services:
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
    environment:
      # 要修正 k1やk2などアクセスキーは本番に即した長い文字列である必要あり
      AZURITE_ACCOUNTS: "a1:k1;a2:k2"
